# ESCUELA POLITÉCNICA NACIONAL

![](logoEpn.jpg){width=3cm height=3cm fig-align="center"}

## Tarea 10 Ejercicios Unidad 04-C | Descomposición LU

### 1. Realice las siguientes multiplicaciones matriz-matriz:

![](Ejercicio1.png){width=7cm height=2,5cm fig-align="center"}

In [1]:
import numpy as np

# a)
A = np.array([[2, -3],
              [3, -1]])
B = np.array([[1, 5],
              [2, 0]])
print("a) A x B =\n", A @ B)

a) A x B =
 [[-4 10]
 [ 1 15]]


In [2]:
# b)
A = np.array([[2, -3],
              [3, -1]])
B = np.array([[1, 5, -4],
              [-3, 2, 0]])
print("\nb) A x B =\n", A @ B)


b) A x B =
 [[ 11   4  -8]
 [  6  13 -12]]


In [3]:
# c)
A = np.array([[2, -3, 1],
              [4, 3, 0],
              [5, 2, -4]])
B = np.array([[0, 1, -2],
              [1, 0, -1],
              [2, 3, -2]])
print("\nc) A x B =\n", A @ B)


c) A x B =
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


In [4]:
# d)
A = np.array([[2, 1, 2],
              [-2, 3, 0],
              [2, -1, 3]])
B = np.array([[1, -2],
              [-4, 1],
              [0, 2]])
print("\nd) A x B =\n", A @ B)


d) A x B =
 [[ -2   1]
 [-14   7]
 [  6   1]]


### 2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices

![](Ejercicio2.png){width=7cm height=3cm fig-align="center"}

In [5]:
import numpy as np

def gauss_jordan(A: np.ndarray) -> np.ndarray:
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    n, m = A.shape
    assert m >= n, "La matriz debe tener al menos n columnas"

    for i in range(n):

        # pivoteo simple
        if A[i, i] == 0:
            for k in range(i + 1, n):
                if A[k, i] != 0:
                    A[[i, k]] = A[[k, i]]
                    break

        if A[i, i] == 0:
            raise ValueError("Matriz singular")

        # normalizar fila pivote
        A[i, :] = A[i, :] / A[i, i]

        # eliminación
        for j in range(n):
            if j != i:
                A[j, :] = A[j, :] - A[j, i] * A[i, :]

    return A

In [6]:
def inversa_por_gauss_jordan(A: np.ndarray):
    det = np.linalg.det(A)
    print("Determinante =", det)

    if abs(det) < 1e-10:
        print("Matriz singular")
        return None

    n = A.shape[0]
    A_aug = np.hstack((A.astype(float), np.eye(n)))

    print("\nMatriz aumentada inicial:\n", A_aug)

    A_rref = gauss_jordan(A_aug)
    A_inv = A_rref[:, n:]

    print("\nMatriz inversa:\n", A_inv)
    return A_inv

In [7]:
A = np.array([
    [4,  2,  6],
    [3,  0,  7],
    [-2, -1, -3]
], dtype=float)

print("Matriz A")
inversa_por_gauss_jordan(A)

Matriz A
Determinante = 0.0
Matriz singular


In [8]:
B = np.array([
    [1, 2,  0],
    [2, 1, -1],
    [3, 1,  1]
], dtype=float)

print("\nMatriz B")
inversa_por_gauss_jordan(B)


Matriz B
Determinante = -8.000000000000002

Matriz aumentada inicial:
 [[ 1.  2.  0.  1.  0.  0.]
 [ 2.  1. -1.  0.  1.  0.]
 [ 3.  1.  1.  0.  0.  1.]]

Matriz inversa:
 [[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]


array([[-0.25 ,  0.25 ,  0.25 ],
       [ 0.625, -0.125, -0.125],
       [ 0.125, -0.625,  0.375]])

In [9]:
C = np.array([
    [1,  1, -1,  1],
    [1,  2, -4, -2],
    [2,  1,  1,  5],
    [-1, 0, -2, -4]
], dtype=float)

print("\nMatriz C")
inversa_por_gauss_jordan(C)


Matriz C
Determinante = 0.0
Matriz singular


In [10]:
D = np.array([
    [4, 0, 0, 0],
    [6, 7, 0, 0],
    [9,11, 1, 0],
    [5, 4, 1, 1]
], dtype=float)

print("\nMatriz D")
inversa_por_gauss_jordan(D)


Matriz D
Determinante = 28.00000000000001

Matriz aumentada inicial:
 [[ 4.  0.  0.  0.  1.  0.  0.  0.]
 [ 6.  7.  0.  0.  0.  1.  0.  0.]
 [ 9. 11.  1.  0.  0.  0.  1.  0.]
 [ 5.  4.  1.  1.  0.  0.  0.  1.]]

Matriz inversa:
 [[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714  0.          0.        ]
 [ 0.10714286 -1.57142857  1.          0.        ]
 [-0.5         1.         -1.          1.        ]]


array([[ 0.25      ,  0.        ,  0.        ,  0.        ],
       [-0.21428571,  0.14285714,  0.        ,  0.        ],
       [ 0.10714286, -1.57142857,  1.        ,  0.        ],
       [-0.5       ,  1.        , -1.        ,  1.        ]])

### 3. Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:

![](Ejercicio3.png){width=7cm height=2cm fig-align="center"}

In [11]:
import numpy as np

def descomposicion_LU(A_in: np.ndarray):
    A = A_in.astype(float).copy() 
    n = A.shape[0]

    L = np.zeros((n, n))
    P = np.eye(n)

    for i in range(n):
        # Pivoteo parcial
        pivot = np.argmax(np.abs(A[i:, i])) + i
        
        if pivot != i:
            A[[i, pivot]] = A[[pivot, i]]
            P[[i, pivot]] = P[[pivot, i]]
            if i > 0:
                L[[i, pivot], :i] = L[[pivot, i], :i]

        L[i, i] = 1

        for j in range(i + 1, n):
            if A[i, i] == 0: 
                raise ValueError("La matriz es singular")
            
            m = A[j, i] / A[i, i]
            A[j, i:] -= m * A[i, i:]
            L[j, i] = m

    # En este punto, A se ha transformado en U
    U = A
    return P, L, U

def resolver_LU(P, L, U, b):
    n = L.shape[0]
    # 1. Ajustar b según la matriz de permutación P
    b_perm = P @ b

    # 2. Sustitución hacia adelante (Ly = Pb)
    y = np.zeros((n, 1))
    for i in range(n):
        y[i] = (b_perm[i] - L[i, :i] @ y[:i]) / L[i, i]

    # 3. Sustitución hacia atrás (Ux = y)
    x = np.zeros((n, 1))
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - U[i, i + 1:] @ x[i + 1:]) / U[i, i]

    return x

In [12]:
import numpy as np

A = np.array([
    [ 1, -1,  2, -1],
    [ 1,  0, -1,  1],
    [ 2,  1,  3, -4],
    [ 0, -1,  1, -1]
], dtype=float)

P, L, U = descomposicion_LU(A)
print("Descomposición realizada con éxito.")

b1 = np.array([6, 4, -2, 5], dtype=float).reshape(-1, 1)
x1 = resolver_LU(P, L, U, b1)
print("\nSolución sistema (a):\n", x1)

Descomposición realizada con éxito.

Solución sistema (a):
 [[ 3.]
 [-6.]
 [-2.]
 [-1.]]


In [13]:
b2 = np.array([1, 1, 2, -1], dtype=float).reshape(-1, 1)

x2 = resolver_LU(P, L, U, b2)
print("Solución sistema (b):\n", x2)

Solución sistema (b):
 [[1.]
 [1.]
 [1.]
 [1.]]


### 4. Encuentre los valores de A que hacen que la siguiente matriz sea singular.

![](Ejercicio4.png){width=2cm height=2cm fig-align="center"}

In [14]:
import sympy as sp

alpha = sp.symbols('alpha')
A = sp.Matrix([
    [1, -1, alpha],
    [2,  2, 1],
    [0, alpha, -sp.Rational(3, 2)]
])

A

Matrix([
[1,    -1, alpha],
[2,     2,     1],
[0, alpha,  -3/2]])

In [15]:
detA = A.det()
print(f"El determinante es: {detA}")

El determinante es: 2*alpha**2 - alpha - 6


In [16]:
sol_alpha = sp.solve(detA, alpha)

print("\nValores de alpha que hacen la matriz singular:")
for i, sol in enumerate(sol_alpha, 1):
    valor_decimal = sol.evalf()
    print(f"alpha_{i} (exacto)  : {sol}")
    print(f"alpha_{i} (decimal) : {valor_decimal:.1f}\n")


Valores de alpha que hacen la matriz singular:
alpha_1 (exacto)  : -3/2
alpha_1 (decimal) : -1.5

alpha_2 (exacto)  : 2
alpha_2 (decimal) : 2.0



### 5. Resuelva los siguientes sistemas lineales:

![](Ejercicio5.png){width=7cm height=3cm fig-align="center"}

In [17]:
# Matrices del sistema (a)
A1 = np.array([
    [1, 0, 0],
    [2, 1, 0],
    [-1, 0, 1]
], dtype=float)

A2 = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
], dtype=float)

b = np.array([2, -1, 1], dtype=float).reshape(-1, 1)

A = A1 @ A2

print("Matriz A =\n", A)

# Descomposición LU
P, L, U = descomposicion_LU(A)

x = resolver_LU(P, L, U, b)
print("Solución x =\n", x)

Matriz A =
 [[ 2.  3. -1.]
 [ 4.  4. -1.]
 [-2. -3.  4.]]
Solución x =
 [[-3.]
 [ 3.]
 [ 1.]]


In [18]:
# Matrices del sistema (b)
B1 = np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
], dtype=float)

B2 = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
], dtype=float)

b = np.array([-1, 3, 0], dtype=float).reshape(-1, 1)

B = B1 @ B2

print("Matriz B =\n", B)

# Descomposición LU
P, L, U = descomposicion_LU(B)

x = resolver_LU(P, L, U, b)
print("Solución x =\n", x)

Matriz B =
 [[ 2.  2.  2.]
 [-1.  0.  1.]
 [ 3.  5.  6.]]
Solución x =
 [[ 0.5]
 [-4.5]
 [ 3.5]]


### 6. Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con lii = 1 para todas las i.

![](Ejercicio6.png){width=7cm height=3cm fig-align="center"}

In [19]:
# Descomposición LU de una matriz 
A = np.array([
    [2, -1, 1],
    [3,  3, 9],
    [3,  3, 5]
], dtype=float)

P, L, U = descomposicion_LU(A)

print("Ejercicio a")
print("Matriz L:")
print(L)

print("\nMatriz U:")
print(U)

Ejercicio a
Matriz L:
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]

Matriz U:
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]


In [20]:
A = np.array([
    [ 1.012, -2.132,  3.104],
    [-2.132,  4.096, -7.013],
    [ 3.104, -7.013,  0.014]
], dtype=float)

P, L, U = descomposicion_LU(A)

print("Ejercicio b")
print("Matriz L:")
print(L)

print("\nMatriz U:")
print(U)

Ejercicio b
Matriz L:
[[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]

Matriz U:
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]


In [21]:
A = np.array([
    [2,  0,   0,   0],
    [1,  1.5, 0,   0],
    [0, -3,   0.5, 0],
    [2, -2,   1,   1]
], dtype=float)

P, L, U = descomposicion_LU(A)

print("Ejercicio c")
print("Matriz L:")
print(L)

print("\nMatriz U:")
print(U)

Ejercicio c
Matriz L:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]

Matriz U:
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]


In [22]:
A = np.array([
    [ 2.1756,  4.0231, -2.1732,  5.1967],
    [-4.0231,  6.0000,  0.0000,  1.1973],
    [-1.0000, -5.2107,  1.1111,  0.0000],
    [ 6.0235,  7.0000,  0.0000, -4.1561]
], dtype=float)

P, L, U = descomposicion_LU(A)

print("Ejercicio d")
print("Matriz L:")
print(L)

print("\nMatriz U:")
print(U)

Ejercicio d
Matriz L:
[[ 1.          0.          0.          0.        ]
 [-0.66790072  1.          0.          0.        ]
 [ 0.36118536  0.14002434  1.          0.        ]
 [-0.16601644 -0.37924771 -0.5112737   1.        ]]

Matriz U:
[[ 6.0235      7.          0.         -4.1561    ]
 [ 0.         10.67530506  0.         -1.57856219]
 [ 0.          0.         -2.1732      6.91885959]
 [ 0.          0.          0.          2.24878393]]


### 7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.

![](Ejercicio7.png){width=8cm height=4cm fig-align="center"}

In [23]:
A = np.array([
    [2, -1, 1],
    [3,  3, 9],
    [3,  3, 5]
], dtype=float)

b = np.array([-1, 0, 4], dtype=float).reshape(-1, 1)

P, L, U = descomposicion_LU(A)
x = resolver_LU(P, L, U, b)

print("Solución a:\n", x)

Solución a:
 [[ 1.]
 [ 2.]
 [-1.]]


In [24]:
A = np.array([
    [ 1.012, -2.132,  3.104],
    [-2.132,  4.096, -7.013],
    [ 3.104, -7.013,  0.014]
], dtype=float)

b = np.array([1.984, -5.049, -3.895], dtype=float).reshape(-1, 1)

P, L, U = descomposicion_LU(A)
x = resolver_LU(P, L, U, b)

print("Solución b:\n", x)


Solución b:
 [[1.]
 [1.]
 [1.]]


In [25]:
A = np.array([
    [2,   0,   0, 0],
    [1, 1.5,   0, 0],
    [0,  -3, 0.5, 0],
    [2,  -2,   1, 1]
], dtype=float)

b = np.array([3, 4.5, -6.6, 0.8], dtype=float).reshape(-1, 1)

P, L, U = descomposicion_LU(A)
x = resolver_LU(P, L, U, b)

print("Solución c:\n", x)

Solución c:
 [[ 1.5]
 [ 2. ]
 [-1.2]
 [ 3. ]]


In [26]:
A = np.array([
    [ 2.1756,  4.0231, -2.1732,  5.1967],
    [-4.0231,  6.0000,  0.0000,  1.1973],
    [-1.0000, -5.2107,  1.1111,  0.0000],
    [ 6.0235,  7.0000,  0.0000, -4.1561]
], dtype=float)

b = np.array([17.102, -6.1593, 3.0004, 0.0], dtype=float).reshape(-1, 1)

P, L, U = descomposicion_LU(A)
x = resolver_LU(P, L, U, b)

print("Solución d:\n", x)

Solución d:
 [[2.9398512 ]
 [0.0706777 ]
 [5.67773512]
 [4.37981223]]


## Link del repositorio GitHub

[github_TamyBenavidez](https://github.com/TamyBenavidez/MN/tree/main/Tarea10), Tarea N°10