# ESCUELA POLITÉCNICA NACIONAL

![](logoEpn.jpg){width=3cm height=3cm fig-align="center"}

## Tarea 11: Ejercicios Unidad 04-D | Gauss-Jacobi y Gauss-Seidel

## 1. Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por medio de $𝐱^{(𝟎)} = 0$:

![](Ejercicio1.png){width=7cm height=3cm fig-align="center"}

In [1]:
import numpy as np

def gauss_jacobi(A, b, x0, n_iter):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    x = np.array(x0, dtype=float)

    n = len(b)

    for k in range(n_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            suma = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - suma) / A[i, i]
        x = x_new
        print(f"x^{k+1} =", x)

    return x

In [2]:
# Ejercicio a
A = [
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
]

b = [1, 0, 4]

x0 = [0, 0, 0]

gauss_jacobi(A, b, x0, n_iter=2)

x^1 = [0.33333333 0.         0.57142857]
x^2 = [ 0.14285714 -0.35714286  0.42857143]


array([ 0.14285714, -0.35714286,  0.42857143])

In [3]:
# Ejercicio b
A = [
    [10, -1,  0],
    [-1, 10, -2],
    [ 0, -2, 10]
]

b = [9, 7, 6]

x0 = [0, 0, 0]

gauss_jacobi(A, b, x0, n_iter=2)

x^1 = [0.9 0.7 0.6]
x^2 = [0.97 0.91 0.74]


array([0.97, 0.91, 0.74])

In [4]:
# Ejercicio c
A = [
    [10,  5,  0,  0],
    [ 5, 10, -4,  0],
    [ 0, -4,  8, -1],
    [ 0,  0, -1,  5]
]

b = [6, 25, -11, -11]

x0 = [0, 0, 0, 0]

gauss_jacobi(A, b, x0, n_iter=2)

x^1 = [ 0.6    2.5   -1.375 -2.2  ]
x^2 = [-0.65   1.65  -0.4   -2.475]


array([-0.65 ,  1.65 , -0.4  , -2.475])

In [5]:
# Ejercicio d
A = [
    [ 4,  1,  1,  0,  1],
    [-1, -3,  1,  1,  0],
    [ 2,  1,  5, -1, -1],
    [-1, -1, -1,  4,  0],
    [ 0,  2, -1,  1,  4]
]

b = [6, 6, 6, 6, 6]

x0 = [0, 0, 0, 0, 0]

gauss_jacobi(A, b, x0, n_iter=2)

x^1 = [ 1.5 -2.   1.2  1.5  1.5]
x^2 = [ 1.325 -1.6    1.6    1.675  2.425]


array([ 1.325, -1.6  ,  1.6  ,  1.675,  2.425])

## 2. Repita el ejercicio 1 usando el método de Gauss-Siedel.

In [6]:
import numpy as np

def gauss_seidel(A, b, x0, n_iter):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    x = np.array(x0, dtype=float)

    n = len(b)

    for k in range(n_iter):
        x_new = x.copy()
        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i, j] * x_new[j]
            x_new[i] = (b[i] - suma) / A[i, i]
        x = x_new
        print(f"x^{k+1} =", x)

    return x

In [7]:
# Ejercicio a
A = [
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
]

b = [1, 0, 4]

x0 = [0, 0, 0]

gauss_seidel(A, b, x0, n_iter=2)

x^1 = [ 0.33333333 -0.16666667  0.5       ]
x^2 = [ 0.11111111 -0.22222222  0.61904762]


array([ 0.11111111, -0.22222222,  0.61904762])

In [8]:
# Ejercicio b
A = [
    [10, -1,  0],
    [-1, 10, -2],
    [ 0, -2, 10]
]

b = [9, 7, 6]

x0 = [0, 0, 0]

gauss_seidel(A, b, x0, n_iter=2)

x^1 = [0.9   0.79  0.758]
x^2 = [0.979  0.9495 0.7899]


array([0.979 , 0.9495, 0.7899])

In [9]:
# Ejercicio c
A = [
    [10,  5,  0,  0],
    [ 5, 10, -4,  0],
    [ 0, -4,  8, -1],
    [ 0,  0, -1,  5]
]

b = [6, 25, -11, -11]

x0 = [0, 0, 0, 0]

gauss_seidel(A, b, x0, n_iter=2)

x^1 = [ 0.6    2.2   -0.275 -2.255]
x^2 = [-0.5       2.64     -0.336875 -2.267375]


array([-0.5     ,  2.64    , -0.336875, -2.267375])

In [10]:
# Ejercicio d
A = [
    [ 4,  1,  1,  0,  1],
    [-1, -3,  1,  1,  0],
    [ 2,  1,  5, -1, -1],
    [-1, -1, -1,  4,  0],
    [ 0,  2, -1,  1,  4]
]

b = [6, 6, 6, 6, 6]

x0 = [0, 0, 0, 0, 0]

gauss_seidel(A, b, x0, n_iter=2)

x^1 = [ 1.5     -2.5      1.1      1.525    2.64375]
x^2 = [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]


array([ 1.1890625 , -1.52135417,  1.86239583,  1.88252604,  2.25564453])

## 3. Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con $TOL = 10_{-3}$.

In [11]:
import numpy as np

def gauss_jacobi_tol(A, b, x0, tol=1e-3, max_iter=100):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    x = np.array(x0, dtype=float)

    n = len(b)

    for k in range(1, max_iter + 1):
        x_new = np.zeros_like(x)
        for i in range(n):
            suma = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - suma) / A[i, i]

        if np.linalg.norm(x_new - x) < tol:
            print(f"Converge en {k} iteraciones")
            return x_new

        x = x_new

    print("No converge en el número máximo de iteraciones")
    return x

In [12]:
# Ejercicio a
A = [
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
]

b = [1, 0, 4]
x0 = [0, 0, 0]

sol_a = gauss_jacobi_tol(A, b, x0)
sol_a

Converge en 10 iteraciones


array([ 0.03507839, -0.23692617,  0.65780145])

In [13]:
# Ejercicio b
A = [
    [10, -1,  0],
    [-1, 10, -2],
    [ 0, -2, 10]
]

b = [9, 7, 6]
x0 = [0, 0, 0]

sol_b = gauss_jacobi_tol(A, b, x0)
sol_b

Converge en 6 iteraciones


array([0.995725, 0.957775, 0.79145 ])

In [14]:
# Ejercicio c
A = [
    [10,  5,  0,  0],
    [ 5, 10, -4,  0],
    [ 0, -4,  8, -1],
    [ 0,  0, -1,  5]
]

b = [6, 25, -11, -11]
x0 = [0, 0, 0, 0]

sol_c = gauss_jacobi_tol(A, b, x0)
sol_c

Converge en 22 iteraciones


array([-0.79758533,  2.79479459, -0.25888879, -2.25187916])

In [15]:
# Ejercicio d
A = [
    [ 4,  1,  1,  0,  1],
    [-1, -3,  1,  1,  0],
    [ 2,  1,  5, -1, -1],
    [-1, -1, -1,  4,  0],
    [ 0,  2, -1,  1,  4]
]

b = [6, 6, 6, 6, 6]
x0 = [0, 0, 0, 0, 0]

sol_d = gauss_jacobi_tol(A, b, x0)
sol_d

Converge en 12 iteraciones


array([ 0.78708833, -1.00303576,  1.86604817,  1.91244923,  1.98957067])

## 4. Utilice el método de Gauss-Siedel para resolver los sistemas lineales en el ejercicio 1, con $TOL = 10_{-3}$.

In [16]:
import numpy as np

def gauss_seidel_tol(A, b, x0, tol=1e-3, max_iter=100):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    x = np.array(x0, dtype=float)

    n = len(b)

    for k in range(1, max_iter + 1):
        x_new = x.copy()
        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i, j] * x_new[j]
            x_new[i] = (b[i] - suma) / A[i, i]

        if np.linalg.norm(x_new - x) < tol:
            print(f"Converge en {k} iteraciones")
            return x_new

        x = x_new

    print("No converge en el número máximo de iteraciones")
    return x

In [17]:
# Ejercicio a
A = [
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
]

b = [1, 0, 4]
x0 = [0, 0, 0]

sol_a = gauss_seidel_tol(A, b, x0)
sol_a

Converge en 6 iteraciones


array([ 0.03535107, -0.23678863,  0.65775895])

In [18]:
# Ejercicio b
A = [
    [10, -1,  0],
    [-1, 10, -2],
    [ 0, -2, 10]
]

b = [9, 7, 6]
x0 = [0, 0, 0]

sol_b = gauss_seidel_tol(A, b, x0)
sol_b

Converge en 4 iteraciones


array([0.9957475 , 0.95787375, 0.79157475])

In [19]:
# Ejercicio c
A = [
    [10,  5,  0,  0],
    [ 5, 10, -4,  0],
    [ 0, -4,  8, -1],
    [ 0,  0, -1,  5]
]

b = [6, 25, -11, -11]
x0 = [0, 0, 0, 0]

sol_c = gauss_seidel_tol(A, b, x0)
sol_c

Converge en 10 iteraciones


array([-0.79730913,  2.79498224, -0.2589884 , -2.25179768])

In [20]:
# Ejercicio d
A = [
    [ 4,  1,  1,  0,  1],
    [-1, -3,  1,  1,  0],
    [ 2,  1,  5, -1, -1],
    [-1, -1, -1,  4,  0],
    [ 0,  2, -1,  1,  4]
]

b = [6, 6, 6, 6, 6]
x0 = [0, 0, 0, 0, 0]

sol_d = gauss_seidel_tol(A, b, x0)
sol_d

Converge en 7 iteraciones


array([ 0.78668253, -1.00271872,  1.86628339,  1.9125618 ,  1.98978976])

## 5. El sistema lineal

![](Ejercicio5.png){width=5cm height=3cm fig-align="center"}

tiene la solución (1, 2, -1)t.
a) Muestre que el método de Jacobi con x(0) = 0 falla al proporcionar una buena aproximación después de 25 iteraciones.

In [21]:
import numpy as np

A = np.array([
    [ 2, -1,  1],
    [ 2,  2,  2],
    [-1, -1,  2]
], dtype=float)

b = np.array([-1, 4, -5], dtype=float)

x = np.zeros(3)

for k in range(25):
    x_new = np.zeros_like(x)
    for i in range(3):
        suma = sum(A[i, j] * x[j] for j in range(3) if j != i)
        x_new[i] = (b[i] - suma) / A[i, i]
    x = x_new

x

array([-20.82787284,   2.        , -22.82787284])

b) Utilice el método de Gauss-Siedel con x(0) = 0:para aproximar la solución para el sistema lineal dentro de 10^−5.

In [22]:
import numpy as np

A = np.array([
    [ 2, -1,  1],
    [ 2,  2,  2],
    [-1, -1,  2]
], dtype=float)

b = np.array([-1, 4, -5], dtype=float)

x = np.zeros(3)
tol = 1e-5
max_iter = 100

for k in range(1, max_iter + 1):
    x_new = x.copy()
    for i in range(3):
        suma = sum(A[i, j] * x_new[j] for j in range(3) if j != i)
        x_new[i] = (b[i] - suma) / A[i, i]

    if np.linalg.norm(x_new - x) < tol:
        print(f"Converge en {k} iteraciones")
        break

    x = x_new

x

Converge en 23 iteraciones


array([ 0.99999571,  2.00000477, -0.99999976])

## 6. El sistema lineal

![](Ejercicio6.png){width=4cm height=3cm fig-align="center"}

tiene la solución (0.9, -0.8, 0.7)t.

a) ¿La matriz de coeficientes

![](Ejercicio6a.png){width=2cm height=2cm fig-align="center"}

tiene diagonal estrictamente dominante?

La matriz no es diagonal estrictamente dominante, aunque Gauss-Seidel puede converger aun así.

b) Utilice el método iterativo de Gauss-Siedel para aproximar la solución para el sistema lineal con una tolerancia de 1022 y un máximo de 300 iteraciones.

In [23]:
import numpy as np

A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)

x = np.zeros(3)
tol = 1e-22
max_iter = 300

for k in range(1, max_iter + 1):
    x_new = x.copy()
    for i in range(3):
        suma = sum(A[i, j] * x_new[j] for j in range(3) if j != i)
        x_new[i] = (b[i] - suma) / A[i, i]

    if np.linalg.norm(x_new - x) < tol:
        print(f"Converge en {k} iteraciones")
        break

    x = x_new

x

array([ 0.9, -0.8,  0.7])

c) ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?

![](Ejercicio6c.png){width=5cm height=3cm fig-align="center"}

El método no converge o converge extremadamente lento y no alcanza la tolerancia dentro de 300 iteraciones.

## 7. Repita el ejercicio 1 usando el método de Jacobi

In [25]:
import numpy as np

A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)

x = np.zeros(3)
tol = 1e-22
max_iter = 300

for k in range(1, max_iter + 1):
    x_new = np.zeros_like(x)
    for i in range(3):
        suma = sum(A[i, j] * x[j] for j in range(3) if j != i)
        x_new[i] = (b[i] - suma) / A[i, i]

    if np.linalg.norm(x_new - x) < tol:
        print(f"Converge en {k} iteraciones")
        break

    x = x_new

x

array([ 0.90025541, -0.80004033,  0.70012933])

El método de Jacobi falla para este sistema, incluso permitiendo muchas iteraciones.

## 8. Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe mediante la ecuación de Laplace. Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar el potencial entre los dos conductores requiere resolver el siguiente sistema lineal.

![](Ejercicio8.png){width=5cm height=3cm fig-align="center"}

a. ¿La matriz es estrictamente diagonalmente dominante?

La matriz es diagonalmente dominante, lo que garantiza la convergencia de Jacobi y Gauss-Seidel.

b. Resuelva el sistema lineal usando el método de Jacobi con $x_(0) = 0$ y $TOL = 10_{-2}$.

In [26]:
import numpy as np

A = np.array([
    [ 4,-1, 0, 0,-1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4,-1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0,-1, 4,-1, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0,-1, 4, 0,-1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 0, 4, 0,-1, 0, 0, 0, 0, 0],
    [ 0, 0, 0,-1, 0, 4, 0,-1, 0, 0, 0, 0],
    [ 0, 0, 0, 0,-1, 0, 4, 0,-1, 0, 0, 0],
    [ 0, 0, 0, 0, 0,-1, 0, 4, 0, 0, 0,-1],
    [ 0, 0, 0, 0, 0, 0,-1, 0, 4,-1, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0,-1, 4,-1, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0,-1, 4,-1],
    [ 0, 0, 0, 0, 0,-1, 0, 0, 0, 0,-1, 4]
], dtype=float)

b = np.array(
    [220,110,110,220,110,110,110,110,220,110,110,220],
    dtype=float
)

x = np.zeros(12)
tol = 1e-2
max_iter = 500

for k in range(1, max_iter + 1):
    x_new = np.zeros_like(x)
    for i in range(12):
        s = sum(A[i,j]*x[j] for j in range(12) if j != i)
        x_new[i] = (b[i] - s) / A[i,i]
    if np.linalg.norm(x_new - x) < tol:
        print(f"Jacobi converge en {k} iteraciones")
        break
    x = x_new

x

Jacobi converge en 15 iteraciones


array([87.99552403, 65.99552412, 65.99552412, 87.99552403, 65.99552412,
       65.99552412, 65.99552412, 65.99552412, 87.99552403, 65.99552412,
       65.99552412, 87.99552403])

c. Repita la parte b) mediante el método de Gauss-Siedel.

In [27]:
x = np.zeros(12)
tol = 1e-2
max_iter = 500

for k in range(1, max_iter + 1):
    x_new = x.copy()
    for i in range(12):
        s = sum(A[i,j]*x_new[j] for j in range(12) if j != i)
        x_new[i] = (b[i] - s) / A[i,i]
    if np.linalg.norm(x_new - x) < tol:
        print(f"Gauss-Seidel converge en {k} iteraciones")
        break
    x = x_new

x

Gauss-Seidel converge en 10 iteraciones


array([87.99492609, 65.99717068, 65.99830315, 87.99894396, 65.99717068,
       65.99933209, 65.99830315, 65.99957409, 87.99894396, 65.99933209,
       65.99957409, 87.99972655])

## Link del repositorio GitHub

[github_TamyBenavidez](https://github.com/TamyBenavidez/MN/tree/main/Tarea11), Tarea N°11